name: Java CI with Maven

# กำหนดให้รันเมื่อมีการ Push โค้ด หรือมีการสร้าง Pull Request ไปที่ branch 'main'
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # 1. Checkout โค้ด
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven # ใช้ Maven Cache เพื่อเร่งความเร็ว
      - name: Run tests
        env:
          SPRING_PROFILES_ACTIVE: test
        run: mvn -B test

  build:
    runs-on: ubuntu-latest # ใช้ Ubuntu เป็น OS สำหรับรัน
    needs: test # รันต่อเมื่อ test เขียวเท่านั้น
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven
      - name: Package
        run: mvn -B -DskipTests verify

  deploy:
    runs-on: ubuntu-latest
    needs: build # รันต่อเมื่อ build เขียวเท่านั้น
    steps:
      - name: Docker Login (ถ้าคุณจะ Deploy จริงจัง)
        # ส่วนนี้จะใช้สำหรับขั้นตอนการสร้างและ Push Docker Image (ขั้นตอนต่อไป)
        if: success()
        run: echo "Build successful and ready for deployment steps..."